### ISSUE TITLE
Cannot connect to Phantom mobile

### ISSUE THREAD

**Issue by 0xDEADBEEFx** [GokiProtocol/walletkit#210]
gm, I don't seem to be able to connect Phantom mobile to my dApp using the walletkit

example: https://beta-app.fsynth.io/#

**Comment by pisomanik** [comment]
Same. It shows up as not installed.

**Comment by 0xDEADBEEFx** [comment]
bump

**Comment by pisomanik** [comment]
Ahh got it. Thanks will try.

**Comment by 0xDEADBEEFx** [comment]
Turns out I just needed to update all dependencies
